USE gatepass;

ALTER TABLE departments
  MODIFY department_name VARCHAR(255) NOT NULL;

INSERT IGNORE INTO departments (department_name, dept_code) VALUES
('B.Tech In Computer Science & Engineering', 'PRG001'),
('B.Tech In Civil Engineering', 'PRG002'),
('Bachelor Of Education', 'PRG003'),
('B.Tech In Mechanical Engineering', 'PRG004'),
('B.Tech In Electronics And Communication Engineering', 'PRG005'),
('B.Sc. In Information Technology', 'PRG006'),
('Bachelor Of Computer Application', 'PRG007'),
('Bachelor Of Arts In Journalism And Mass Communication', 'PRG008'),
('Bachelor Of Library Science', 'PRG009'),
('B.Com.(Bachelor OF Commerce)', 'PRG010'),
('Bachelor Of Arts', 'PRG011'),
('Bachelor Of Business Administration', 'PRG012'),
('Bachelor Of Arts And Bachelor Of Legislative Law', 'PRG013'),
('Bachelor Of Legislative Law', 'PRG014'),
('B. Tech In Electrical & Electronics Engineering', 'PRG015'),
('Bsc In Nursing', 'PRG016'),
('Bachelor Of Science In Yoga', 'PRG017'),
('Bachelor Of Physiotherapy', 'PRG018'),
('Bachelor In Medical Lab Technician', 'PRG019'),
('Bachelor Of Science In Physics', 'PRG020'),
('Bachelor Of Science In Chemistry', 'PRG021'),
('Bachelor Of Science In Mathematics', 'PRG022'),
('Bachelor Of Science In Forensic Sciences', 'PRG023'),
('B.Sc. In Botany', 'PRG024'),
('B.Sc. In Biotechnology', 'PRG025'),
('B.Sc. In Microbiology', 'PRG026'),
('B.Sc. In Zoology', 'PRG027'),
('Bachelor Of Education (Part Time)', 'PRG028'),
('Bachelor Of Physical Education', 'PRG029'),
('Bachelor Of Physical Education And Sports', 'PRG030'),
('Bachelor Of Pharmacy', 'PRG031'),
('B.Sc. In Computer Science', 'PRG032'),
('B.Sc. In Data Science', 'PRG033'),
('Bachelor Of Science (Honours) Agriculture', 'PRG034'),
('Post Basic B.Sc. Nursing Programme (2-Year Programme For Diploma Nurses)', 'PRG035'),
('B.Tech In Computer Science Engineering (AI/ML)', 'PRG036'),
('B.Tech In Computer Science Engineering (Data Science)', 'PRG037'),
('BBA In Hospital Administration', 'PRG038'),
('BBA (Business Analytics) SAMATRIX', 'PRG039'),
('B.Tech (M.E.) (Digital Manufacturing Using AI And CPS)', 'PRG040'),
('B.Tech (EEE) (Smart Semiconductor Device & Sustainable Power Engineering With AI Integration)', 'PRG041'),
('B.Tech. (E.C.E.) (Semi-Conductor Design Framework For Industrial ICs)', 'PRG042'),
('BCA Full Stack Web Development (Java)', 'PRG043'),
('BCA AIML In Collaboration With Samatrix', 'PRG044'),
('B Sc DS AIML In Collaboration With IBM', 'PRG045'),
('B Sc CS AIML In Collaboration With IBM', 'PRG046'),
('B Sc IT AIML In Collaboration With IBM', 'PRG047'),
('B.Tech.(CSE) (Data Science) With Samatrix.io', 'PRG048'),
('B.Tech. (CSE) (Full Stack Web Development) With L&T', 'PRG049'),
('B.Tech AIML With SAMATRIX', 'PRG050'),
('B.Com Banking & Finance In Collaboration With IIBF', 'PRG051'),
('B.Com Practitioner Approach To Finance Essentials', 'PRG052');
